apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
    - name: container1
      image: alpine
      command: ["/bin/sh", "-c"]
      args: ["touch /container1/container1.txt && sleep 3600"]
      volumeMounts:
        - name: shared-data
            : /container1
    - name: container2
      image: alpine
      command: ["/bin/sh", "-c"]
      args: ["touch /container2/container2.txt && sleep 3600"]
      volumeMounts:
        - name: shared-data
          mountPath: /container2
