apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
    - name: container1
      image: alpine
      command: ['sh', '-c', 'echo The Bench Container 1 is Running ; sleep 3600']
      volumeMounts:
        - name: shared-data
          mountPath: /container1
    - name: container2
      image: alpine
      command: ['sh', '-c', 'echo The Batch Container is Running ; sleep 3600']
      volumeMounts:
        - name: shared-data
          mountPath: /container2
