apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostpath-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hostpath-app
  template:
    metadata:
      labels:
        app: hostpath-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - hostpath-app
            topologyKey: kubernetes.io/hostname
      containers:
      - name: my-container
        image: nginx
        volumeMounts:
        - name: hostpath-volume
          mountPath: /hostpath
      volumes:
      - name: hostpath-volume
        hostPath:
          path: /workervolume
          type: Directory